# Generated by Django 2.2.4 on 2019-08-08 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbookapp', '0003_askcomment_askre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='askcomment',
            old_name='askcontents',
            new_name='contents',
        ),
        migrations.RenameField(
            model_name='askre',
            old_name='askcontents',
            new_name='contents',
        ),
        migrations.RemoveField(
            model_name='askcomment',
            name='askpost',
        ),
        migrations.RemoveField(
            model_name='askre',
            name='askcomment',
        ),
        migrations.AddField(
            model_name='askcomment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cbookapp.CodeAsk'),
        ),
        migrations.AddField(
            model_name='askre',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='cbookapp.AskComment'),
        ),
    ]
