# Generated by Django 2.2.4 on 2019-08-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbookapp', '0004_auto_20190808_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='askre',
            old_name='contents',
            new_name='recontents',
        ),
    ]
