# Generated by Django 2.2.4 on 2019-08-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbookapp', '0006_auto_20190808_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='askre',
            old_name='recontents',
            new_name='contents',
        ),
        migrations.RenameField(
            model_name='sharere',
            old_name='recontents',
            new_name='contents',
        ),
    ]
