# Generated by Django 2.2.2 on 2019-08-09 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cbookapp', '0007_auto_20190808_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharecomment',
            name='com_writer',
            field=models.CharField(default='any_user', max_length=50),
        ),
        migrations.AddField(
            model_name='sharere',
            name='re_writer',
            field=models.CharField(default='any_user', max_length=50),
        ),
        migrations.AlterField(
            model_name='codeshare',
            name='writer',
            field=models.CharField(default='any_user', max_length=50),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbookapp.ShareComment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
