# Generated by Django 2.2.2 on 2019-08-09 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cbookapp', '0009_auto_20190809_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeshare',
            name='like_user_set',
            field=models.ManyToManyField(blank=True, related_name='like_user_set', through='cbookapp.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
