# Generated by Django 2.2.2 on 2019-08-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbookapp', '0010_codeshare_like_user_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='askcomment',
            name='com_writer',
            field=models.CharField(default='any_user', max_length=50),
        ),
        migrations.AddField(
            model_name='askre',
            name='re_writer',
            field=models.CharField(default='any_user', max_length=50),
        ),
    ]
